'use client';

import { SiteHeader } from "@/components/site-header";
import { Card, CardContent } from '@/components/ui/card';
import { DrawAuditsWidget } from '@/components/draw-audits-widget';

export default function AuditsPage() {
    return (
        <div className="min-h-screen bg-background">
            <SiteHeader />
            <div className="container mx-auto px-4 py-8 max-w-7xl pt-32">
                <div className="space-y-8">
                    {/* Enhanced Header Section */}
                    <div className="flex flex-col lg:flex-row lg:items-end justify-between">
                        <div>
                            <div className="flex items-center gap-2 mb-2">
                                <h1 className="text-3xl font-bold tracking-tight text-foreground">Public Audit Chain</h1>
                            </div>
                            <p className="text-muted-foreground text-lg">
                                <strong>Every draw. Every operator. Fully verifiable.</strong><br />
                                This is the independent, tamper-evident audit ledger generated by the CAFAAS integrity system.<br />
                                Anyone can inspect, verify, and trace the history of competition draws — openly and transparently.
                            </p>
                        </div>
                    </div>

                    <Card className="bg-transparent">
                        <CardContent className="py-0">
                            <div className="flex items-start gap-3">
                                <div>
                                    <h4 className="text-sm font-semibold text-blue-500 mb-1">How it works</h4>
                                    <div className="text-sm text-muted-foreground  flex flex-col gap-2">
                                        <p>
                                            Every time an operator completes a draw, CAFAAS generates a unique cryptographic signature and links it to the previous record.
                                        </p>
                                        <p>This creates a permanent, uneditable chain of custody that proves:</p>
                                        <ul className="list list-disc list-inside">
                                            <li>The draw happened exactly when recorded</li>
                                            <li>The result hasn't been changed</li>
                                            <li>The order of events is authentic</li>
                                            <li>No operator can backdate, remove, or manipulate results</li>
                                        </ul>
                                        <p>Anyone can inspect any draw, from any operator, at any time.</p>
                                    </div>
                                </div>
                            </div>
                        </CardContent>
                    </Card>

                    {/* Draw Audits Widget */}
                    <DrawAuditsWidget
                        showOperator={true}
                        publicView={true}
                        title="All verified draws"
                        description="A complete, chronological ledger of all competition prize draws conducted through CAFAAS. Each entry is cryptographically validated and publicly available forever."
                    />
                </div>
            </div>
        </div>
    );
}
